# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - post1.md
  - post2.md
  - post3.md

#footer: ''

#style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag

collections:
  습작:
    output: true
    permalink: /습작/:title/
